AllCops:
  Exclude:
    - '**/Gemfile'
  TargetRubyVersion: 3.4

Metrics/BlockLength:
  AllowedMethods:
    - describe
    - context

Metrics/PerceivedComplexity:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/ParameterLists:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/AbcSize:
  # Disable "Assignment Branch Condition size for update_attributes is too high" from houndci
  # because codeclimate already give that for us with more details
  Enabled: false

Layout/LineLength:
  Max: 125

Style/Alias:
  Enabled: false

Style/PerlBackrefs:
  Enabled: false

Layout/TrailingEmptyLines:
  Enabled: false

# Override the HoundCI custom rules (they do not use Rubocop defaults)
Style/StringLiterals:
  EnforcedStyle: single_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: single_quotes

Layout/ExtraSpacing:
  # disabling that in favour of using:
  # long_field_test_1 = 1
  # field_test_2      = 2
  # etc               = 3
  Enabled: false

Style/BlockDelimiters:
  Enabled: false

Style/CollectionMethods:
  Enabled: false

Style/SignalException:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/CommentAnnotation:
  Enabled: false

Layout/DotPosition:
  EnforcedStyle: leading

Style/GuardClause:
  Enabled: false

Style/RegexpLiteral:
  Enabled: false

Lint/SuppressedException:
  Enabled: false

Lint/AssignmentInCondition:
  Enabled: false

Style/DoubleNegation:
  Enabled: false

Style/AndOr:
  Enabled: false

Style/ClassVars:
  Enabled: false

Style/GlobalVars:
  Enabled: false

Style/SingleLineBlockParams:
  Enabled: false

Style/RescueModifier:
  Enabled: false

Style/ColonMethodCall:
  Enabled: false

Naming/FileName:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/RescueStandardError:
  Enabled: false

Security/YAMLLoad:
  Enabled: false

Naming/MemoizedInstanceVariableName:
  Enabled: false
