source 'https://rubygems.org'

# Load the base shoryuken gem
gemspec path: '../../../'

group :test do
  gem 'activejob', '~> 7.0.0'
  gem 'httparty'
  gem 'multi_xml'
  gem 'simplecov'
  gem 'warning'

  # Rails 7.0 + Ruby 3.4 compatibility fixes
  gem 'mutex_m'
  gem 'logger'
  gem 'ostruct'
end