name: Specs
on:
  - push
  - pull_request
permissions:
  contents: read
jobs:
  specs:
    name: Specs
    strategy:
      matrix:
        ruby: ['3.2', '3.3', '3.4', '4.0']
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3

      - uses: ruby/setup-ruby@12fd324f1d0b43274fdc8130f6980590a667c455 # v1.312.0
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true

      - name: Run specs
        run: bundle exec rake spec

  integrations:
    name: Integrations
    strategy:
      matrix:
        ruby: ['3.2', '3.3', '3.4', '4.0']
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3

      - name: Start ElasticMQ
        run: docker compose up -d

      - name: Wait for ElasticMQ
        run: |
          timeout 30s bash -c '
          until curl -s http://localhost:9324/health; do
            echo "Waiting for ElasticMQ..."
            sleep 1
          done
          '

      - uses: ruby/setup-ruby@12fd324f1d0b43274fdc8130f6980590a667c455 # v1.312.0
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true

      - name: Run integration specs
        run: bundle exec rake spec:integration

  ci-success:
    name: CI Success
    runs-on: ubuntu-latest
    if: always()
    needs:
      - specs
      - integrations
    steps:
      - name: Check all jobs passed
        if: |
          contains(needs.*.result, 'failure') ||
          contains(needs.*.result, 'cancelled') ||
          contains(needs.*.result, 'skipped')
        run: exit 1
      - run: echo "All CI checks passed!"
